<?php
abstract class Generator
{
	protected $project;
	protected $source;

	public function __construct($project)
	{
		$this->project = $project;
	}
	
	public function write($filename='')
	{
		$fh = fopen($filename, "w");
		fwrite($fh, $this->source);
		fclose($fh);
	}
	
	protected function classHeader($classname, $extends='', $additionalComments='')
	{
		$classname = Utils::camelcase($classname, true);
		if($extends)
		{
			$extends = ' extends ' . $extends;
		}
		if($additionalComments)
		{
			$additionalComments = "\n * " . str_replace("\n", "\n * ", $additionalComments);
		}
		$time = date("c");
		$header = <<<HEADER
<?php

/**
 * $classname
 * 
 * Automatically generated by Bene at $time$additionalComments
 */	

class $classname$extends
{

HEADER;
		return $header;
	}
	
	protected function classFooter()
	{
		$footer = <<<FOOTER

}
?>

FOOTER;
		return $footer;
	}
	
	protected function classVar($fieldname, $value='')
	{
		$fieldname = Utils::camelcase($fieldname);
		if($value)
		{
			return '	private $' . $fieldname . ' = ' . var_export($value, true) . ";\n";
		}
		else
		{
			return '	private $' . $fieldname . ";\n";
		}
	}
}
?>